name: hola mundo #nombre del workflow

on: [push]

jobs:
  hola: #nombre del job
    runs-on: ubuntu-latest  #se ejecuta en un servidor, cada job nececita uno

    steps: #tareas
      - name: Hola mundo #nombre de tarea
        run: echo "hla mundo " #tarea a realizar
      
      - name: archivo
        run: touch hola.txt

      - name: contentido
        run: echo "¡Hola desde el archivo!" > hola.txt
      
      - name: imprimir-archivo
        run: cat hola.txt
  job-ls-1: #nombre del job
    runs-on: ubuntu-latest   #se ejecuta en un servidor, cada job nececita uno

    steps: #tareas
      - name: ejecuta-ls #nombre de tarea
        run: ls #tarea a realizar